name: "build React project"
on: push
jobs:
  npm-build:
    runs-on: ubuntu-22.04
    steps:
      - name: "read content form repo"
        uses: actions/checkout@v4.2.2
      - name: "install dependencies"
        run: npm install
      - name: "package the project"
        run: npm run build